{pkgs,...}:

{ home.packages = with pkgs; [
	nixos-generators
        nix-search-cli
        nix-output-monitor
        nix-init
        lxde.lxsession
        gtk-engine-murrine
        pkg-config
        zsh
        oh-my-zsh
        zip
        xz
        unzip
        p7zip
        ripgrep
        psmisc 
        fzf    
        gnupg
        mtr    
        iperf
        dnsutils      
        nmap    
        ipcalc  
        tree
        lsof
        sysstat
        lm_sensors
        ncdu
        ethtool
        pciutils 
        usbutils
        qrencode
        pptp
        pptpd
        ppp
        jq     
        yq-go
        gh
        calc
        python3
        glfw
        gnumake
        nodejs
        rustup
        hugo
        go
        eza
        zoxide
        grim
        slurp
        swappy
        xclip
        feh
        pywal        
        wofi
        xwayland
        wayland-scanner
        wl-clipboard
        waybar
        clipman
        wlsunset
        wdisplays
        wireguard-tools
        yt-dlp
        gallery-dl
        playerctl
        pulseaudio
        coreutils-prefixed
        dunst
        libnotify
        hyprshot 
        hyprcursor
        nwg-look
        swtpm
        ueberzugpp
        ffmpegthumbnailer
        w3m 
        pulsemixer
        xboxdrv

        # Desktop Apps
        ark
        telegram-desktop
        filezilla
        remmina
        qbittorrent
        pavucontrol
        pasystray
        blueman
        obsidian
        feishin
        gimp
        font-manager
        zathura
        evince
        yacreader
        nicotine-plus
        picard
        duckstation
        pcsx2
        rpcs3
    
      ];
    }
