{pkgs,inputs,...}:

{ home.packages = with pkgs; [
	nixos-generators
        nix-search-cli
        nix-output-monitor
        xfce.xfconf
        lxde.lxsession
        zsh
        oh-my-zsh
        zip
        xz
        unzip
        p7zip
        ripgrep
        psmisc 
        fzf    
        mtr    
        iperf
        dnsutils      
        nmap    
        ipcalc  
        tree
        lsof
        sysstat
        lm_sensors 
        ethtool
        pciutils 
        usbutils
        pptp
        pptpd
        ppp
        jq     
        yq-go
        nodejs
        rustup
        hugo
        go
        eza
        zoxide
        ranger
        grim
        slurp
        swappy
        xclip
        feh
        pywal        
        waybar
        wofi
        xwayland
        wl-clipboard
        wireguard-tools
        yt-dlp
        gallery-dl
        playerctl
        pulseaudio
        coreutils-prefixed
        dunst
        libnotify
        hyprpaper
        hyprlock
        hyprshot 
        nwg-look

        # Desktop Apps
        firefox
        telegram-desktop
        filezilla
        qbittorrent
        gparted
        obsidian
        vscode
        feishin
        gimp
        inkscape
        font-manager
        zathura
        nicotine-plus
        picard
    
      ];
    }
